apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: syash7202/server-app
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    #argocd-image-updater.argoproj.io/backend.pull-secret: dockerhub-creds
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/backend.allow-tags: "regexp:^\\d+$"
spec:
  project: default
  source:
    repoURL: https://github.com/syash7202/argo-helm-manifests.git
    targetRevision: master
    path: base-chart
    helm:
      releaseName: backend
      valueFiles:
        - custom-helm-values/backend/values-backend.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
