apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root
  namespace: default
  finalizers:
    - resources-finalizer.argoproj.io/apps-of-apps
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/syash7202/argo-helm-manifests.git
    targetRevision: master
    path: argocd/argocd-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
